# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 21:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('motivo', models.TextField(default='')),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('solicitante', models.CharField(default='', max_length=1024)),
                ('receptor', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='', max_length=1024)),
                ('vacantes', models.IntegerField(default=0)),
                ('tipo_cargo', models.CharField(choices=[('N', 'Nuevo'), ('R', 'Reemplazo')], default='N', max_length=1)),
                ('tipo_jornada', models.CharField(choices=[('P', 'Part-time'), ('F', 'Full-time')], default='P', max_length=1)),
                ('sueldo', models.FloatField(default=0)),
                ('comentarios', models.TextField(default='')),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('solicitante', models.CharField(default='', max_length=1024)),
                ('receptor', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
