# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
    ]
