# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1', '0002_auto_20151211_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='reclutador',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
